# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnSX6lvY-ZQfHphdrvquoXNGnNYLFWad
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

df = pd.read_csv('ECG_train.csv')

df

X = df.drop('target', axis = 1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

test = pd.read_csv('ECG_test.csv')

test['target'] = clf.predict(test)

res = test['target']

test.to_csv('res.csv')
a = open("res.csv").read().replace("\n", ",").split(",")
f = []
for i in len(1,range(a)):
    if i%2==0:
        f.append(a[i])
fo = open("res1.txt", "w")
fo.write(",".join(f))



